---
#  _     _ _              ____ ____  _      __          __     ___            _        
# | |   (_) |__  _ __ ___/ ___/ ___|| |    / /__ _ __ __\ \   / / |_ __ _ ___| | _____ 
# | |   | | '_ \| '__/ _ \___ \___ \| |   | / __| '__/ __| | / /| __/ _` / __| |/ / __|
# | |___| | |_) | | |  __/___) |__) | |___| \__ \ | | (__| |/ / | || (_| \__ \   <\__ \
# |_____|_|_.__/|_|  \___|____/____/|_____| |___/_|  \___| /_/   \__\__,_|___/_|\_\___/
#                                          \_\          /_/                            
# tasks file for ar-libressl-src
- include: install-pkg.yml
- include: get-archive.yml
- include: compile-src.yml
- include: make-config.yml

